### ISSUE TITLE
error    services.AddHostedService<JwtRefreshTokenCache>(); in startup.cs

### ISSUE THREAD

**Issue by khoanb83** [dotnet-labs/JwtAuthDemo#4]
hi !
I have issue 
dotnet C:\JwtAuthDemo-master\webapi\JwtAuthDemo\app\build\JwtAuthDemo.dll
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'JwtAuthDemo.Infrastructure.JwtTokenConfig' while attempting to activate 'JwtAuthDemo.Infrastructure.JwtAuthManager'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Cal
please help!

**Comment by changhuixu** [comment]
Probably you missed these two lines.

https://github.com/dotnet-labs/JwtAuthDemo/blob/master/webapi/JwtAuthDemo/Startup.cs#L30-L31
